name:                xmonad-config
version:             0.18.0
github:              "byhowe/xmonad"
license:             BSD-3-Clause
author:              "Ömer Faruk Çavuş"
maintainer:          "byhowe@proton.me"
copyright:           "2024 Ömer Faruk Çavuş"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/byhowe/xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- data-default-class
- X11
- xmonad >= 0.18
- xmonad-contrib >= 0.18

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  xmonad:
    main:                xmonad.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config

  xmobar:
    main:                xmobar.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmobar
