#!/bin/sh

export WINIT_X11_SCALE_FACTOR=1

# optimus-manager
# Note: /usr/bin/prime-switch is called before calling startx
# in the fish shell configuration. This is IMPORTANT.
/usr/bin/prime-offload

# Computer specific monitor settings
gpu=$(optimus-manager --print-mode | awk '{ print $5 }')

# For some reason, xrandr refuses to work if i don't call
# it like this before actually setting the options.
xrandr
# NVIDIA GPU
if [ "$gpu" = "nvidia" ]; then
  # Setup edp-hdmi
  #xrandr --output "eDP-1-1" --primary --mode 1920x1080 --pos 0x0 --rotate normal \
  #       --output "HDMI-1-1" --mode 1920x1080 --pos 1920x0 --rotate normal \
  #       --output "DP-1-1" --off \
  #       --output "HDMI-1-2" --off

  # Setup edp-dp
  xrandr --output "eDP-1-1" --primary --mode 1920x1080 --pos 0x0 --rotate normal \
         --output "HDMI-1-1" --off \
         --output "DP-1-1" --mode 1366x768 --pos 1920x0 --rotate normal \
         --output "HDMI-1-2" --off
fi

# Integrated GPU
if [ "$gpu" = "integrated" ] || [ "$gpu" = "hybrid" ]; then
  # Default driver
  #xrandr --output "eDP-1" --mode 1920x1080 --pos 0x0 --rotate normal \
  #       --output "HDMI-1" --mode 1920x1080 --pos 1920x0 --rotate normal \
  #       --output "DP-1" --off \
  #       --output "HDMI-2" --off 

  # Setup edp-dp
  # xf86-video-intel
  xrandr --output "eDP1" --primary --mode 1920x1080 --pos 0x0 --rotate normal \
         --output "DP1" --mode 1366x768 --pos 1920x0 --rotate normal \
	 --output "HDMI1" --off \
         --output "HDMI2" --off \
         --output "VIRTUAL1" --off

  # Setup edp-hdmi
  # xf86-video-intel
  #xrandr --output "eDP1" --primary --mode 1920x1080 --pos 0x0 --rotate normal \
  #       --output "DP1" --off \
  #       --output "HDMI1" --mode 1920x1080 --pos 1920x0 --rotate normal \
  #       --output "HDMI2" --off \
  #       --output "VIRTUAL1" --off
fi

xset s off -dpms
xset r rate 300 50 # Faster keyboard input

picom --config ~/.config/picom/picom.conf&
dunst&
lxpolkit&
pcmanfm -d&

# Run the window manager
qtile start
